### ISSUE TITLE
Add linear Search 

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#1]

**Comment by Nikzy7** [comment]
Hey @ankitapuri .. Can you please specify the language?

**Comment by sifat009** [comment]
I'm interested to work on this issue.

**Comment by hridyakrishna** [comment]
Can I work on this?

**Comment by ankitapuri** [comment]
Make a folder regarding it and then add code in these following along with README
Python
C++
C
Java
JavaScript
README.md file with explanation of the algorithm
P.S if a folder exists then add into it

**Comment by ankitapuri** [comment]
In which language you will work @hridyakrishna @sifat009

**Comment by hridyakrishna** [comment]
> In which language you will work @hridyakrishna @sifat009

I have given a pull request by creating a directory named Linear_search and added C programming code into it

**Comment by tarishij17** [comment]
I'll pick Java

**Comment by tarishij17** [comment]
https://github.com/ankitapuri/DSA-guide/pull/8

> I'll pick Java

**Comment by sahilsinghal** [comment]
can we write in golang as well?

**Comment by sahilsinghal** [comment]
can i pick it for java if not assigned to anyone else?

**Comment by ankitapuri** [comment]
> can we write in golang as well?

no please

**Comment by ankitapuri** [comment]
> can i pick it for java if not assigned to anyone else?

its done

**Comment by sifat009** [comment]
> In which language you will work @hridyakrishna @sifat009

javascript.

**Comment by ankitapuri** [comment]
> > In which language you will work @hridyakrishna @sifat009
> 
> javascript.

Ok and if possible create a readme for it so that I can close this issue
