### ISSUE TITLE
Generate Permutations

### ISSUE THREAD

**Issue by krishrahul98** [ankitapuri/DSA-guide#112]
**Problem Statement**
Given an integer array A of size N denoting a collection of numbers, return all possible permutations.

Language:

- [x] C++

**Comment by ankitapuri** [comment]
are using recursion for this @krishrahul98 or what other approach

**Comment by krishrahul98** [comment]
Using recursion @ankitapuri

**Comment by ankitapuri** [comment]
okay add it in the recursion folder
