### ISSUE TITLE
Add N-queens problem 

### ISSUE THREAD

**Issue by Jainchhavi16** [ankitapuri/DSA-guide#135]
Add N-queens problem to backtracking folder.

**Comment by Jainchhavi16** [comment]
HI, I would like to work on this issue , please assign it to me.

**Comment by MananOO12** [comment]
> HI, I would like to work on this issue , please assign it to me.

I've already submited the PR for this Algorithm 3 days ago.
#115 
I guess you have to wait till that PR is merged.
Also it was in C++ so you can do it in other languages.

**Comment by Jainchhavi16** [comment]
I'll add it in python than
Thanks

**Comment by ankitapuri** [comment]
@Jainchhavi16 @MananOO12 wait for sometime and let me review it first.

**Comment by PrakashAditya17** [comment]
If this is also required , I can do in java @ankitapuri

**Comment by VaishnaviKP** [comment]
@ankitapuri  ,can i please work on this in   C programming
