### ISSUE TITLE
Add heap sort 

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#16]
Make a folder regarding it and then add code in these following along with README
Python
C++
C
Java
JavaScript
README.md file with explanation of the algorithm

**Comment by rangolucas** [comment]
I can solve this for Python, Java and JS

**Comment by ketanshahapure** [comment]
I will implement it in Java

**Comment by ankitapuri** [comment]
> I will implement it in Java

@ketanshahapure go head please and make a folder for it

**Comment by ankitapuri** [comment]
> I can solve this for Python, Java and JS
specify any 1 language

**Comment by ketanshahapure** [comment]
> > I will implement it in Java
> 
> @ketanshahapure go head please and make a folder for it

Working on it!

**Comment by rangolucas** [comment]
I'll go with Python then!

**Comment by rangolucas** [comment]
I'll go with Python then!

**Comment by ankitapuri** [comment]
> I'll go with Python then!

ok

**Comment by praneethacl** [comment]
Hi, can I do this in Cpp?

**Comment by ankitapuri** [comment]
> Hi, can I do this in Cpp?

go ahead

**Comment by hridyakrishna** [comment]
Can I do this in C?

**Comment by adarshvulli** [comment]
> Can I do this in C?

@hridyakrishna, let us wait for some time! if none, you can go with it! since you already got a merged PR

**Comment by hridyakrishna** [comment]
> @hridyakrishna, let us wait for some time! if none, you can go with it! since you already got a merged PR

Okay sure...Thank you...

**Comment by ankitapuri** [comment]
Any updates @rangolucas

**Comment by rangolucas** [comment]
> Any updates @rangolucas

I'll be done tomorrow

**Comment by abhi2694** [comment]
@ankitapuri  would like to take this up and do it in java.

**Comment by ankitapuri** [comment]
> @ankitapuri would like to take this up and do it in java.

its done in java look for other issues please

**Comment by shiladityaroy212** [comment]
Please assign this to me. I can do this in C and C++. Specify any one

**Comment by ankitapuri** [comment]
> Please assign this to me. I can do this in C and C++. Specify any one

do it in C

**Comment by shiladityaroy212** [comment]
Sure, will give it as soon as possible .

**Comment by shiladityaroy212** [comment]
> > Please assign this to me. I can do this in C and C++. Specify any one
> 
> do it in C

I have done the program of heap sort in C. Please have a look to it

**Comment by koshtaayush** [comment]
@ankitapuri Let me know for JS. Will wait. If not assigned to anyone I can pick.

**Comment by PrakashAditya17** [comment]
If its still left in C , do assign me.
