### ISSUE TITLE
would like to add selection sort

### ISSUE THREAD

**Issue by Sloth-Panda** [ankitapuri/DSA-guide#160]
would like to make this as part of cwoc

**Comment by hardikchitkara** [comment]
I can provide selection sort in any language. Please assign this task to me. I'll get it done asap. I am doing this under CrossWoc.

**Comment by Sloth-Panda** [comment]
@hardikchitkara bro, if you want to contribute you should make your own issue to go ahead with that, Anways chill

**Comment by ankitapuri** [comment]
@Sloth-Panda the selection sort is already done . Kindly look into some other issues or provide a idea which is not done yet.
