### ISSUE TITLE
I want to add comments to all the files

### ISSUE THREAD

**Issue by yashlikescode** [ankitapuri/DSA-guide#164]
comments are very necessary
the make us understand the codes easily
there are very less fines in your repo which have comments in them,
comments have too much importance in coding tests of many companies,
thats why I have choosen this issue.

This is under crosswoc
i dont know how to add labels on issues

**Comment by hardikchitkara** [comment]
i can add comments in any of the given code in all given languages. Please assign this task to me.

**Comment by kmryashasvi** [comment]
@hardikchitkara It is already assigned to me

**Comment by ankitapuri** [comment]
@hardikchitkara  u can add comments on the rest of the files which are remaining
