### ISSUE TITLE
link to Contribution Guidelines not linked properly in README.md

### ISSUE THREAD

**Issue by rakesh0x7** [ankitapuri/DSA-guide#165]
![broken link](https://user-images.githubusercontent.com/60481830/107843597-7f49fa80-6df2-11eb-94aa-72faad0ce35c.png)

I would like to fix this issue under CrossWoc.
@ankitapuri could you please assign it to me

**Comment by ankitapuri** [comment]
Okay !! Also add the contributing guidelines if anything is missing

**Comment by rakesh0x7** [comment]
I have updated the README.md.
we can close this issue.
Thank you @ankitapuri
