### ISSUE TITLE
2D - Matrices problem 

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#166]
Create a Directory naming Matrices .
Under it create a folder naming C and then add a file writing the code of Tridiagonal Matrix

**Comment by epicdeepak** [comment]
can i work on this ?

**Comment by epicdeepak** [comment]
@ankitapuri can you please elaborate it a bit like input and output conditions?

**Comment by ankitapuri** [comment]
Basic idea is to create a tridiagonal matrix 
Ask the user to input the order of matrix .
Then accordingly ask the  elements required for tridiagonal matrix to be inputted by the user . And later print the output in matrix form
