### ISSUE TITLE
2D-Matrix Problem 

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#167]
Create a Directory naming Matrices .
Under it create a folder naming C++ and then add a file writing the code of Tridiagonal Matrix

**Comment by Amit366** [comment]
I can work on this issue

**Comment by yashlikescode** [comment]
May I add a code for it in python?
assign me and get the job done same day...
(except when you assign me when its my sleeping time, then work will  be done next day)
🥺

**Comment by kiruba-r11** [comment]
@ankitapuri Can I work on this in C++.

**Comment by yashlikescode** [comment]
> May I add a code for it in python?
> assign me and get the job done same day...
> (except when you assign me when its my sleeping time, then work will be done next day)
> 🥺

What happened?
Should I proceed or not?

**Comment by Amit366** [comment]
@ankitapuri I have sent a PR. It isn't merged
