### ISSUE TITLE
2D - matrix problem 

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#172]
Create a Directory naming Matrices .
Under it create a folder naming Python and then add a file writing the code of Tridiagonal Matrix

**Comment by Sloth-Panda** [comment]
would like to work on this

**Comment by swetakb15** [comment]
@ankitapuri If this is still open will you please assign this to me

**Comment by kiruba-r11** [comment]
@ankitapuri I would like to work on this if it's still open. I can implement it in both python and C++.

**Comment by ankitapuri** [comment]
> @ankitapuri I would like to work on this if it's still open. I can implement it in both python and C++.

do it in python
