### ISSUE TITLE
addition of issue, pr templates, welcome and greeting bots

### ISSUE THREAD

**Issue by Sloth-Panda** [ankitapuri/DSA-guide#180]
let me know if you want to get this done and assign me for the same

welcome bot config file will be having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out

https://github.com/apps/welcome

**Comment by ankitapuri** [comment]
> let me know if you want to get this done and assign me for the same
> 
> welcome bot config file will be having a proper message that will show up when any user will open up an issue or pull-request for the first time.
> For reference, check out
> 
> https://github.com/apps/welcome

cool go ahead

**Comment by Sloth-Panda** [comment]
@ankitapuri can I know how are you keeping track of the prs and the individual people's points?

**Comment by ankitapuri** [comment]
I am maintaining the google sheet where I am writing the PR merged and the score according to difficulty .
