### ISSUE TITLE
selection sort in js

### ISSUE THREAD

**Issue by Sloth-Panda** [ankitapuri/DSA-guide#185]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Would like to show selection sort in javascript with example
### Have you read the *Contributing Guidelines on Pull Requests* ?

(Write your answer here.)
Yes

**Comment by Sloth-Panda** [comment]
@ankitapuri  would like to work on this issue

**Comment by ankitapuri** [comment]
U should check the repo before creating issues . Its already done .
