### ISSUE TITLE
Higher order array methods in js

### ISSUE THREAD

**Issue by Sloth-Panda** [ankitapuri/DSA-guide#186]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Would like to show different higher order array methods using javascript
### Have you read the *Contributing Guidelines on Pull Requests* ?

(Write your answer here.)
Yes

**Comment by Sloth-Panda** [comment]
@ankitapuri  would like to work on this issue

**Comment by ankitapuri** [comment]
Join the discord channel once so that I can discuss in detail : https://discordapp.com/channels/798445199176892447/798445619215466506/810035803887501362

**Comment by Sloth-Panda** [comment]
@ankitapuri can you provide your peojects server's discord this is the link for the whole cwoc server

**Comment by ankitapuri** [comment]
> @ankitapuri can you provide your peojects server's discord this is the link for the whole cwoc server
https://discord.gg/fK9f8qyY
