### ISSUE TITLE
I will add a readme file to all the techniques

### ISSUE THREAD

**Issue by yashlikescode** [ankitapuri/DSA-guide#188]
Guidance via code is okay, but many students between us like to understand and get the things easily with the help of documentation.
 That's why I want to add a readme file to all the techniques used in this repo.

For example,
In the directory of bubble sort,
I will add a readme file which will contain definition, mechanisms, etc., which will make the user understand the topic easily.
Thank you

**Comment by yashlikescode** [comment]
And don't worry.
This time I will do my duty to all of the files. (Unlike the case when I was not able to add comments to some of the files)
Because I have only to do the documentation, coding is not required much.

And please don't set difficulty of the issue as "easy" because there are a large number of techniques mentioned and it will take time.

**Comment by ankitapuri** [comment]
Join the discord link once so that I can discuss in detail : https://discordapp.com/channels/798445199176892447/798445619215466506/810035803887501362

**Comment by kanak22** [comment]
Can I work on this ? 
As I think it's a lot of documentation for only a single person.. so can I also contribute?

**Comment by yashlikescode** [comment]
all directories have their readme files only recursion's readme is needed, rest have to be edited only

**Comment by yashlikescode** [comment]
> all directories have their readme files only recursion's readme is needed, rest have to be edited only

@kanak22
