### ISSUE TITLE
Bead Sort in C++

### ISSUE THREAD

**Issue by m-code12** [ankitapuri/DSA-guide#190]
I would like to work on this as a part of CrossWoc 2021. @ankitapuri Could you assign it to me?

**Comment by arbazalam01** [comment]
Can i work on it

**Comment by m-code12** [comment]
> Can i work on it

@arbazalam01 
I am already working on it and will raise a pr soon.

**Comment by ankitapuri** [comment]
> > Can i work on it
> 
> @arbazalam01
> I am already working on it and will raise a pr soon.
U were unassigned @m-code12 bcoz everyone gets a period of 6 days to do .

**Comment by m-code12** [comment]
Really sorry for the delay @ankitapuri , I had my exams in between, I wasn't aware of the 6 days period. I'll keep this in mind in future and this shall never be repeated.
 I have raised a PR for it.

**Comment by ankitapuri** [comment]
> Really sorry for the delay @ankitapuri , I had my exams in between, I wasn't aware of the 6 days period. I'll keep this in mind in future and this shall never be repeated.
> I have raised a PR for it.

okay
