### ISSUE TITLE
Add Cross WOC Banner or Poster

### ISSUE THREAD

**Issue by Ayush7614** [ankitapuri/DSA-guide#192]
## Is your feature request related to a problem? Please describe.
Add Cross WOC Banner or Poster

## Describe the solution you'd like
Add Cross WOC to  Banner or Poster

**Comment by ankitapuri** [comment]
I want to extend this issue . In addition to adding poster , add the github stats cards . 
Features required : 
- no of issues open
- no of issues closed
- no of pull requests open
- no of pull requests closed
- no of forks 
- no of stars 
- no of contributors

**Comment by Ayush7614** [comment]
Okk you can assign me i will do this all things @ankitapuri under crosswoc
