### ISSUE TITLE
leaders in an array

### ISSUE THREAD

**Issue by Sloth-Panda** [ankitapuri/DSA-guide#216]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

finding leaders in an array
### Have you read the *Contributing Guidelines on Pull Requests* ?

(Write your answer here.)

YES

**Comment by Sloth-Panda** [comment]
@ankitapuri would like to work on it using python/c++

**Comment by kanak22** [comment]
I would like to work on this in C++

**Comment by yashlikescode** [comment]
If the problem is  about selecting string from a given array,
I can work on it using C,
I will pull request the same day issue is assigned

**Comment by abhinav5481** [comment]
Hi @ankitapuri 
I would like to work on this issue using JavaScript. Please assign it to me
