### ISSUE TITLE
hey .. @ankitapuri ,.. I want to add some recursion problems like harmonic sum of n-1 , geometric sum of n-1 and some complex math problems too.,..in Python . so can you please assign this issue to me?? for contribution in CrossWoc.

### ISSUE THREAD

**Issue by Mansi3546** [ankitapuri/DSA-guide#222]

**Comment by ankitapuri** [comment]
will u use recursion?

**Comment by Mansi3546** [comment]
In whatever way you want,.. I can solve that problems,.. If you will assign with recursion ,.then I will go with it otherwise in normal way. I mentioned recursion because there are only 3 problems solved in recursion topic with Python till now.

**Comment by ankitapuri** [comment]
> In whatever way you want,.. I can solve that problems,.. If you will assign with recursion ,.then I will go with it otherwise in normal way. I mentioned recursion because there are only 3 problems solved in recursion topic with Python till now.

do through recursion
