### ISSUE TITLE
Stack using c

### ISSUE THREAD

**Issue by saimanoharhm** [ankitapuri/DSA-guide#226]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I would like to contribute stack programs using c language. Could you pls assign this for me
### Have you read the *Contributing Guidelines on Pull Requests* ?

(Write your answer here.)

yes

**Comment by saimanoharhm** [comment]
@ankitapuri Could you pls assign this for me. Can I work on c,c++ and java. If not I will work on c

**Comment by saimanoharhm** [comment]
@ankitapuri Could you pls assign this for me

**Comment by ankitapuri** [comment]
What problem of stack will u implement ?
