### ISSUE TITLE
Queues using c

### ISSUE THREAD

**Issue by saimanoharhm** [ankitapuri/DSA-guide#228]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I would like to contribute few Queue programs. 
### Have you read the *Contributing Guidelines on Pull Requests* ?

(Write your answer here.)
Yes

**Comment by saimanoharhm** [comment]
@ankitapuri Could you pls assign this for me. Can I work on c,c++ and java. If not I will work on c

**Comment by ankitapuri** [comment]
What programs please specify .
