### ISSUE TITLE
Add merge sort

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#23]
Make a folder regarding it and then add code in these following along with README
Python
C++
C
Java
JavaScript
README.md file with explanation of the algorithm

**Comment by Sahith02** [comment]
I can do this in python and C++.

**Comment by ankitapuri** [comment]
> I can do this in python and C++.

Create a folder and go ahead

**Comment by Jaideep07** [comment]
I would like to do in C and JAVA can you assign it to me.

**Comment by Sahith02** [comment]
> > I can do this in python and C++.
> 
> Create a folder and go ahead

Sure, will do!

**Comment by Kartik987** [comment]
hey @ankitapuri . I just created a PR  for merge sort as per the instructions  in readme.md. Please have a look on it and if appropriate please merge it.

**Comment by ankitapuri** [comment]
@Kartik987 can you please make a PR just with java and readme 
because the rest is done by @Sahith02

**Comment by Kartik987** [comment]
ok.

**Comment by Kartik987** [comment]
please check. I have just added with java only.

**Comment by ankitapuri** [comment]
> > I can do this in python and C++.
> 
> Create a folder and go ahead

@Sahith02 just add in the folder made

**Comment by Sahith02** [comment]
#25 Done I have added python right now. Will add C++ soon.

**Comment by Sahith02** [comment]
#25 I've added merge sort in C++ as well. Please review and merge.

**Comment by koshtaayush** [comment]
@ankitapuri I would like to do it in JS

**Comment by ankitapuri** [comment]
> @ankitapuri I would like to do it in JS

ok

**Comment by ankitapuri** [comment]
> I would like to do in C and JAVA can you assign it to me.

would u like to do it in C @Jaideep07

**Comment by RAMYA-CP** [comment]
Hey I would like to do it in c can i take this up?

**Comment by Jaideep07** [comment]
> > I would like to do in C and JAVA can you assign it to me.
> 
> would u like to do it in C @Jaideep07 

👍🏻 will do it
