### ISSUE TITLE
All MARKDOWN files that needs to be rendered should be README.md

### ISSUE THREAD

**Issue by vybhav72954** [ankitapuri/DSA-guide#248]
**Describe the bug**
----
- All across the Repo, some markdown files that should be rendered are either called README.md or have a Trivial Name like `Heap Sort.md`.

So there are 2 scenarios:

1. All algorithm documentation files should be rendered **(preferably)** and hence should be renamed to `README.md`
1. None of the documentation files should be rendered **(can be useful in some cases, not here as per my understanding)** and then should have the name resembling the algorithm.

**The REPO should follow one naming convention.**

**To Reproduce**
----
- Steps to reproduce the behavior:
  1. Go to `DSA-guide/Sorting_Techniques/Wave_Sort/` and there is a `README.md` file which GitHub renders automatically.
  2. Go to `DSA-guide/Sorting_Techniques/Heap_Sort/` and there is a `Heap Sort.md` file which GitHub wont renders.

**Expected behavior**
-----
- For files meant for the same purpose, there should be one naming convention only.

**Possible solution**
----
- Rename all markdown to `README.md` (only those which should be rendered of course).

**Comment by ankitapuri** [comment]
Would u like to solve it

**Comment by vybhav72954** [comment]
Yes please

**Comment by vybhav72954** [comment]
@ankitapuri I have opened 5 issues #242 #247 - #250

You can assign me all those which you think are required in the Repo

**Comment by vybhav72954** [comment]
> Would u like to solve it

And do tell me what you want, should I rename each fie to README so that they are rendered or should I rename to Algorithm name.

**Comment by ankitapuri** [comment]
> > Would u like to solve it
> 
> And do tell me what you want, should I rename each fie to README so that they are rendered or should I rename to Algorithm name.

keep the name README.md and I can't assign all issues to 1 person . It needs to be done 1 at a time .

**Comment by vybhav72954** [comment]
> > > Would u like to solve it
> > 
> > 
> > And do tell me what you want, should I rename each fie to README so that they are rendered or should I rename to Algorithm name.
> 
> keep the name README.md and I can't assign all issues to 1 person . It needs to be done 1 at a time .

I will complete them on the go I guess XD

**Comment by vybhav72954** [comment]
@ankitapuri Can you put the labels for CrossWoc, I believe difficulty label is required!

**Comment by ankitapuri** [comment]
> @ankitapuri Can you put the labels for CrossWoc, I believe difficulty label is required!

it is required on the issues. not on the PRs .

**Comment by vybhav72954** [comment]
> > @ankitapuri Can you put the labels for CrossWoc, I believe difficulty label is required!
> 
> it is required on the issues. not on the PRs .

What I actually meant was, that on the Issue there are 3 labels- `CrossWoC, bug, good first issue`.

None of which as per my knowledge are difficulty label that CrossWoc Require
