### ISSUE TITLE
Deepest Leaves Sum

### ISSUE THREAD

**Issue by abhinav5481** [ankitapuri/DSA-guide#268]
**Is your feature request related to a problem? Please describe.**
----
- A very popular DSA question on binary trees -  Given the root of a binary tree, return the sum of values of its deepest leaves.

**Describe the solution you'd like**
----
- I would like to get it solved in Java.

I would like to work on this problem in Java, @ankitapuri please assign it to me.

**Comment by abhinav5481** [comment]
I would like to work on this in Java as part of CrossWoc. Please assign it to me.

**Comment by ankitapuri** [comment]
> I would like to work on this in Java as part of CrossWoc. Please assign it to me.

@abhinav5481 I'm not taking solutions in Java language

**Comment by abhinav5481** [comment]
Okay,
I can do it in Python as well. Or if you want me to implement it in a particular language then please tell me.

**Comment by abhinav5481** [comment]
I will be working as a part of Crosswoc'21 . Please add a label of CrossWoc.
