### ISSUE TITLE
towers of hanoi 

### ISSUE THREAD

**Issue by rakesh0x7** [ankitapuri/DSA-guide#269]
## 💥 Proposal

I would like add toh using recursion in cpp

### Have you read the *Contributing Guidelines on Pull Requests* ?

- [X] yes

**Comment by ankitapuri** [comment]
okay

**Comment by Akash20x** [comment]
I want to solve this problem in python. Please assign me this issue as a part of Cross Woc

**Comment by abhinav5481** [comment]
I would like to work on it in Java Script. Please assign it to me.

**Comment by rakesh0x7** [comment]
@ankitapuri can you close this?

**Comment by ankitapuri** [comment]
> @ankitapuri can you close this?

Its not required to close
