### ISSUE TITLE
Add Readme.md to linear search 

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#27]
Add a readme to linear search describing it

**Comment by someshnarwade** [comment]
Can you assign this issue to me? 
I'd like to work on it.

**Comment by amitShindeGit** [comment]
I have made a PR regarding the issue, kindly check it.Happy to help.

**Comment by ankitapuri** [comment]
> Can you assign this issue to me?
> I'd like to work on it.

Its already done can you look into other issues . There also we require a Readme.
