### ISSUE TITLE
Compare the strings by frequency of the smallest character.

### ISSUE THREAD

**Issue by abhinav5481** [ankitapuri/DSA-guide#275]
## 💥 Proposal

Let the function f(s) be the frequency of the lexicographically smallest character in a non-empty string s. For example, if s = "dcce" then f(s) = 2 because the lexicographically smallest character is 'c', which has a frequency of 2.

You are given an array of strings words and another array of query strings queries. For each query queries[i], count the number of words in words such that f(queries[i]) < f(W) for each W in words.

Return an integer array answer, where each answer[i] is the answer to the ith query.

**Comment by abhinav5481** [comment]
Hi
I would like to work on this as part of crossWoc'21. I can do it in Python. Please assign it to me in Python

**Comment by kiruba-r11** [comment]
@ankitapuri can I work on this in C++ under CrossWoc
