### ISSUE TITLE
 K-diff Pairs in an Array

### ISSUE THREAD

**Issue by abhinav5481** [ankitapuri/DSA-guide#279]
## 💥 Proposal

Given an array of integers nums and an integer k, return the number of unique k-diff pairs in the array.
A k-diff pair is an integer pair (nums[i], nums[j]), where the following are true:
0 <= i, j < nums.length
i != j
|nums[i] - nums[j]| == k
Notice that |val| denotes the absolute value of val.

### Have you read the *Contributing Guidelines on Pull Requests* ?
yes

**Comment by abhinav5481** [comment]
Hi @ankitapuri 
I would like to work on it in python under crossWoc'21. Please assign it to me.

**Comment by pri1311** [comment]
I would like to do it in c++
