### ISSUE TITLE
Wanted to add sum of digits using recursion in c

### ISSUE THREAD

**Issue by UG-SEP** [ankitapuri/DSA-guide#297]
## 💥 Proposal

Hey,
I wanted to add sum of digits problem using recursion in c language
`Example:`
`Input:` 5434
`Output:` The sum of digits is 16 
### Have you read the *Contributing Guidelines on Pull Requests* ?

(Yes I have readed )

Please assign me

**Comment by rish-singhal** [comment]
@ankitapuri  I can do the same in python. Assign me if possible.
