### ISSUE TITLE
Add binary search 

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#3]

**Comment by IMPrimph** [comment]
@ankitapuri 
I would like to do that

**Comment by sifat009** [comment]
I'm interested to work on this issue.

**Comment by Mayankjha997** [comment]
i would like to do in c language

**Comment by NidhiNivedita6** [comment]
Please assign me this. I want to do this in C++

**Comment by saiharsha-22** [comment]
@ankitapuri I would like to work on this issue, I will do in Java programming and I will add traversal also ca you assign this issue to me

**Comment by sethivansh6** [comment]
I can code it in C++, JAVA and JS. Please assign it to me!

**Comment by ankitapuri** [comment]
Make a folder regarding it and then add code in these following along with README
Python
C++
C
Java
JavaScript
README.md file with explanation of the algorithm
P.S if a folder exists then add into it

**Comment by ankitapuri** [comment]
please select the language @sifat009 @sethivansh6 @NidhiNivedita6 @Mayankjha997

**Comment by sethivansh6** [comment]
@ankitapuri I will do it in JAVA.

**Comment by ankitapuri** [comment]
> @ankitapuri I will do it in JAVA.

Ok make a folder and send the PR

**Comment by Mayankjha997** [comment]
@ankitapuri  is c language acceptable

**Comment by ankitapuri** [comment]
> > @ankitapuri I will do it in JAVA.
> 
> Ok make a folder and send the PR

okay

**Comment by NidhiNivedita6** [comment]
I will do it in C++

**Comment by ankitapuri** [comment]
> @ankitapuri is c language acceptable

okay

**Comment by Mayankjha997** [comment]
I will do it in C language
please assign me

**Comment by NidhiNivedita6** [comment]
I will do it in C++. Please assign me.

**Comment by sethivansh6** [comment]
@ankitapuri isn't your repo registered for hacktoberfest?

**Comment by ankitapuri** [comment]
> @ankitapuri isn't your repo registered for hacktoberfest?

it is! please check the topics

**Comment by ankitapuri** [comment]
> I will do it in C++. Please assign me.

ok @NidhiNivedita6

**Comment by ankitapuri** [comment]
@NidhiNivedita6 its already done in cpp 
you can choose from remaining

**Comment by NidhiNivedita6** [comment]
So can I do in C?

**Comment by ankitapuri** [comment]
@Mayankjha997 is currently doing in it

**Comment by koshtaayush** [comment]
@ankitapuri I would like to do it in JS

**Comment by ankitapuri** [comment]
> @ankitapuri I would like to do it in JS

okay

**Comment by Mayankjha997** [comment]
@ankitapuri  I did in c++ ; @NidhiNivedita6  can do it in c

**Comment by ankitapuri** [comment]
@NidhiNivedita6  go ahead with C

**Comment by koshtaayush** [comment]
> > @ankitapuri I would like to do it in JS
> 
> okay

> @ankitapuri Raised a PR for JS

**Comment by hridyakrishna** [comment]
@ankitapuri Can I work on this? (C language)

**Comment by ankitapuri** [comment]
> @ankitapuri Can I work on this? (C language)

Its already done

**Comment by hridyakrishna** [comment]
@ankitapuri  Is java done? Can you please assign for it?
