### ISSUE TITLE
Add binary search in python

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#30]
Add binary search in python in the folder already made

**Comment by Harsh-Udai** [comment]
@ankitapuri  i would like to do this , plz assim me this

**Comment by Shreyash0713** [comment]
@ankitapuri I would like to work on it. Please assign it to me.

**Comment by ankitapuri** [comment]
> @ankitapuri i would like to do this , plz assim me this

ok @HarshUdai

**Comment by ankitapuri** [comment]
> @ankitapuri I would like to work on it. Please assign it to me.

you can refer to other issues as well.

**Comment by Harsh-Udai** [comment]
@ankitapuri  hey, i have made a pr please check.
