### ISSUE TITLE
Add Counting Sort

### ISSUE THREAD

**Issue by tahmid02016** [ankitapuri/DSA-guide#35]
Make a folder regarding it and then add code in these following along with README
Python
C++
C
Java
JavaScript
README.md file with explanation of the algorithm

**Comment by tahmid02016** [comment]
I am doing this in Python

**Comment by SHARC-99** [comment]
> Make a folder regarding it and then add code in these following along with README
> Python
> C++
> C
> Java
> JavaScript
> README.md file with explanation of the algorithm

I am doing it on all the languages...

**Comment by Mownika25** [comment]
Hi, Can I solve it in java?

**Comment by ankitapuri** [comment]
> > Make a folder regarding it and then add code in these following along with README
> > Python
> > C++
> > C
> > Java
> > JavaScript
> > README.md file with explanation of the algorithm
> 
> I am doing it on all the languages...
just do it in C++, C and JS along with  a readme

**Comment by ankitapuri** [comment]
> > Make a folder regarding it and then add code in these following along with README
> > Python
> > C++
> > C
> > Java
> > JavaScript
> > README.md file with explanation of the algorithm
> 
> I am doing it on all the languages...

just do it in C++, C and JS along with  a readme @SHARC-99

**Comment by ankitapuri** [comment]
> Hi, Can I solve it in java?

yes go ahead

**Comment by hridyakrishna** [comment]
@ankitapuri  Can I do it in C?

**Comment by praneethacl** [comment]
Hi, can I do this in python?
