### ISSUE TITLE
Add Bubble Sort

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#4]

**Comment by sethivansh6** [comment]
I can do it!

**Comment by saiharsha-22** [comment]
@ankitapuri I will do in c++

**Comment by ankitapuri** [comment]
Make a folder regarding it and then add code in these following along with README
Python
C++
C
Java
JavaScript
README.md file with explanation of the algorithm
P.S if a folder exists then add into it

**Comment by theAkashDas** [comment]
Hello @ankitapuri can I implement this using C?

**Comment by ankitapuri** [comment]
yeah sure @saiharsha-22 in c++ and @theAkashDas  in C

**Comment by theAkashDas** [comment]
Hello @ankitapuri in hacktoberfest website it is showing ineligible repo. Can you please look into this?

**Comment by ankitapuri** [comment]
> Hello @ankitapuri in hacktoberfest website it is showing ineligible repo. Can you please look into this?
I'll get back to you

**Comment by ankitapuri** [comment]
@theAkashDas refer Readme.md once

**Comment by hridyakrishna** [comment]
@ankitapuri  Can I work on this using java?

**Comment by ankitapuri** [comment]
> @ankitapuri Can I work on this using java?

Only in C++ and python is left

**Comment by hridyakrishna** [comment]
@ankitapuri  Okay, Shall I work on it in python?

**Comment by MaxJaycee** [comment]
@ankitapuri I can also do it in c++ and python
