### ISSUE TITLE
Add Quick sort

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#5]

**Comment by NidhiNivedita6** [comment]
Can I do this in C?

**Comment by saiharsha-22** [comment]
@ankitapuri I would like to do in c++

**Comment by ankitapuri** [comment]
Make a folder regarding it and then add code in these following along with README
Python
C++
C
Java
JavaScript
README.md file with explanation of the algorithm
P.S if a folder exists then add into it

**Comment by krabhisharma** [comment]
I will do it for java @ankitapuri

**Comment by ArchanaDhaker** [comment]
I would like to do in Python.

**Comment by Mownika25** [comment]
Can I do it in Java?

**Comment by ankitapuri** [comment]
> I would like to do in Python.

yeah go ahead

**Comment by ankitapuri** [comment]
> Can I do it in Java?

its done already

**Comment by koshtaayush** [comment]
@ankitapuri I would like to do it in JS

**Comment by ankitapuri** [comment]
> @ankitapuri I would like to do it in JS

Let others be given a chance , if no-one wants to take it then you can do it @koshtaayush

**Comment by koshtaayush** [comment]
@ankitapuri sure

**Comment by ankitapuri** [comment]
> Can I do it in Java?

Do you wanna do it in java @Mownika25

**Comment by RAMYA-CP** [comment]
Hey I would like to implement it in c

**Comment by praneethacl** [comment]
> > Can I do it in Java?
> 
> Do you wanna do it in java @Mownika25

I will do it in java.

**Comment by ankitapuri** [comment]
> Make a folder regarding it and then add code in these following along with README
> Python
> C++
> C
> Java
> JavaScript
> README.md file with explanation of the algorithm
> P.S if a folder exists then add into it

**Code in JS along with a Readme**

**Comment by shruti512** [comment]
Can I add it in JS?

**Comment by ankitapuri** [comment]
> @ankitapuri sure

@koshtaayush  Do u want to do it ???

**Comment by koshtaayush** [comment]
Yeah @ankitapuri 
I'll do

**Comment by ankitapuri** [comment]
> Yeah @ankitapuri
> I'll do

Do both the code and readme.

**Comment by debajitdeb11** [comment]
Hey, @ankitapuri I want to add few more programs under this category. Can you please assign me?

**Comment by ricardosmithco** [comment]
Please assign this to me and I can do in Java :)

**Comment by ankitapuri** [comment]
> Hey, @ankitapuri I want to add few more programs under this category. Can you please assign me?

I have already assigned this  and once done I'll close this issue . please look for other issues

**Comment by Srithanya** [comment]
Can I do it in python?

**Comment by khandelwalsarvesh** [comment]
I can do this in python3 ,JS, please assign me in which language is remaining.Thanks.

**Comment by ankitapuri** [comment]
> Yeah @ankitapuri
> I'll do

updates @koshtaayush ??

**Comment by koshtaayush** [comment]
> > Yeah @ankitapuri
> > I'll do
> 
> updates @koshtaayush ??

Raised PR @ankitapuri
