### ISSUE TITLE
Add shell sort

### ISSUE THREAD

**Issue by tahmid02016** [ankitapuri/DSA-guide#57]
I can do this in C++ and Python.

**Comment by ankitapuri** [comment]
> I can do this in C++ and Python.

ok

**Comment by sifat009** [comment]
I would love to do this in javascript.

**Comment by anmol193** [comment]
can i do this in java?

**Comment by anmol193** [comment]
> can i do this in java?

@ankitapuri

**Comment by ankitapuri** [comment]
> can i do this in java?

Any updates @anmol193

**Comment by anmol193** [comment]
> > can i do this in java?
> 
> Any updates @anmol193

done @ankitapuri

**Comment by Mithunitp** [comment]
Can i do in C language?

**Comment by PrakashAditya17** [comment]
I am ready to code this in java, just order it and I am coding it.

**Comment by ankitapuri** [comment]
> I am ready to code this in java, just order it and I am coding it.

its already done
