### ISSUE TITLE
Add selection sort

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#69]
Add code in these following along with README
Python
C++
Java
JavaScript
README.md file with explanation of the algorithm

**Comment by Aniruddha8699** [comment]
@ankitapuri I would like to work on Selection sort in C++. Kindly assign me.
And if required I can also add the Ternary Search folder.

**Comment by SaurabhVj** [comment]
I would like to write this algorithm in java. Kindly assign me this.

**Comment by keivalya** [comment]
I can do it in Python. Please assign it to me.

**Comment by AakritiKinra** [comment]
I would like to do this in C language. Kindly assign me.

**Comment by ankitapuri** [comment]
> I would like to do this in C language. Kindly assign me.

It's already done in C

**Comment by sethivansh6** [comment]
@ankitapuri I can do this and heap sort in java...if you want....assign it to me.

**Comment by rahulatrkm** [comment]
I can do it in python/java. Kindly assign it to me.

**Comment by rai1410swati** [comment]
Hi! I can work on this issue in java and python language. Kindly assign this issue to me.

**Comment by OMEGAeNcore** [comment]
I can do this in Python, Java and C++. Kindly assign this task to me.

**Comment by ankitapuri** [comment]
@OMEGAeNcore  @rai1410swati  I just want a code in JS and readme 
If anyone of u is interested then you can tell me once and continue

**Comment by samjones246** [comment]
Hey, I can do this in JS :)

**Comment by OMEGAeNcore** [comment]
I can do this in js.

**Comment by ankitapuri** [comment]
> I can do this in js.

ok 
Also make a readme for selection sort
