### ISSUE TITLE
Add Insertion Sort 

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#7]

**Comment by sethivansh6** [comment]
@ankitapuri I can work on this issue as well others and that too in C++, JAVA, and JS. Assign it to me!

**Comment by saiharsha-22** [comment]
@ankitapuri I would like to do in c++

**Comment by ankitapuri** [comment]
Make a folder regarding it and then add code in these following along with README
Python
C++
C
Java
JavaScript
README.md file with explanation of the algorithm

**Comment by ankitapuri** [comment]
@saiharsha-22 please do it in C++ and @sethivansh6 do it in JAVA, and JS

**Comment by tahmid02016** [comment]
I can do it in Python

**Comment by ADARSHULTIMATE** [comment]
@tahmid02016 please do it python

**Comment by ankitapuri** [comment]
> I can do it in Python

yes

**Comment by ketanshahapure** [comment]
@ankitapuri Hey, do you want me to implement Heap sort in Java? If yes, please create a new issue for it. Thanks!

**Comment by ankitapuri** [comment]
> @ankitapuri Hey, do you want me to implement Heap sort in Java? If yes, please create a new issue for it. Thanks!

surely I'll create one

**Comment by praneethacl** [comment]
Hi, can I do this in python?

**Comment by ankitapuri** [comment]
> Hi, can I do this in python?

Its left only in JS

**Comment by sifat009** [comment]
I would like to implement it on javascript

**Comment by ankitapuri** [comment]
> I would like to implement it on javascript

ok
