### ISSUE TITLE
Add programs involving recursion in the following languages 

### ISSUE THREAD

**Issue by ankitapuri** [ankitapuri/DSA-guide#74]
Programs involving recursion in 
C
C++
Java
Python
JS

Add them in their respective folders

**Comment by vedanttttt** [comment]
I can do it , assign to me !

**Comment by ankitapuri** [comment]
> I can do it , assign to me !

Just add any 1 program and that too in any 1 language

**Comment by vedanttttt** [comment]
Okay

**Comment by anmol193** [comment]
can i do this using java?

**Comment by SaurabhVj** [comment]
I would like to write code in c++ @ankitapuri

**Comment by shubhamc1200** [comment]
Can I write the height of the binary tree problem using recursion in java?

**Comment by shubhamc1200** [comment]
Thank you

**Comment by samriddhi-arya** [comment]
Can I write 'print subsets of sum k in an array' using recursion in java?

**Comment by TejasPodutwar** [comment]
Hey @ankitapuri I would like to add reverse of a string using recursion problem!!
Could you pls assign this issue to me?

**Comment by varad64** [comment]
Hi @ankitapuri I'd love to do this using Java. Could you please assign it to me?

**Comment by shruti512** [comment]
Hi, I would like to add code for finding palindrome in cpp

**Comment by adityashukla11** [comment]
I just added two programs of Recursion in Java.

**Comment by ayush-agr** [comment]
Hi @ankitapuri Please review my pr for string reverse in c++ using recursion -> https://github.com/ankitapuri/DSA-guide/pull/83
Thanks

**Comment by adityashukla11** [comment]
Hello, I would like to add the following two Recursion programs in Java : 
1 : Convert Decimal to Binary.
2 : Print all possible combinations of N-dice Rolls

**Comment by ankitapuri** [comment]
> Hey @ankitapuri I would like to add reverse of a string using recursion problem!!
> Could you pls assign this issue to me?

specify the language as well

**Comment by sethivansh6** [comment]
@ankitapuri I have added many problems in recursion in java like subset, string permutation, josephus problem, checking palindrome allow me to push the code.

Thanks

**Comment by PrinceKhatick** [comment]
I want to work on this, assign this to me

**Comment by varad64** [comment]
> Hi @ankitapuri I'd love to do this using Java. Could you please assign it to me?

@ankitapuri I've pushed the PR Java code for Tower of Hanoi

**Comment by SandeepGamot** [comment]
Hey @ankitapuri, I can contribute a bunch of recursion solutions here, 
does this require assignment or is it ok to directly push a PR?

**Comment by ankitapuri** [comment]
> Hey @ankitapuri, I can contribute a bunch of recursion solutions here,
> does this require assignment or is it ok to directly push a PR?

Don't add so many codes please it takes a lot of effort to review it

**Comment by ut-01** [comment]
I want to contribute Fibonacci sequence using recursion in JavaScript.

**Comment by abhijay-w** [comment]
Hello @ankitapuri, I would like to add the solution of the Staircase Problem in Java.

**Comment by ankitapuri** [comment]
I am closing this issue for some time 
those who were assigned can still continue
