### ISSUE TITLE
Add Jump Search

### ISSUE THREAD

**Issue by tahmid02016** [ankitapuri/DSA-guide#93]
I can add it in C++ and Python

**Comment by Zaman3027** [comment]
Please assign this to me I can do it in java

**Comment by anirudhwalia** [comment]
I can do it in JAVA, I'd be happy if you assigned it to me.

**Comment by PragatiJ55** [comment]
I can add the documentation for Jump search

**Comment by ankitapuri** [comment]
> Please assign this to me I can do it in java

ok

**Comment by ankitapuri** [comment]
> I can add the documentation for Jump search

ok

**Comment by khandelwalsarvesh** [comment]
i can do it in python .Can you assign me this?

**Comment by ankitapuri** [comment]
> i can do it in python .Can you assign me this?

its done

**Comment by khandelwalsarvesh** [comment]
Can I do it in js?

**Comment by PrakashAditya17** [comment]
I can code it in Java or C whichever language is left.

**Comment by rapunzel127** [comment]
Can I do it in cpp?

**Comment by ankitapuri** [comment]
> I can code it in Java or C whichever language is left.

Do it in C
